export type Config = {
  DEFAULT_MAX_MANA: number;
  DEFAULT_AP_PER_TURN: number;
  DEFAULT_ATTACK_AP_COST: number;
  DEFAULT_ABILITY_AP_COST: number;
  DEFAULT_MAX_MOVEMENTS_PER_TURN: number;
  STARTING_MANA: number;
  HALF_DAMAGE_MITIGATION_THRESHOLD: number;
};

export const defaultConfig: Config = {
  DEFAULT_MAX_MANA: 5,
  DEFAULT_AP_PER_TURN: 1,
  DEFAULT_ATTACK_AP_COST: 1,
  DEFAULT_ABILITY_AP_COST: 1,
  DEFAULT_MAX_MOVEMENTS_PER_TURN: 3,
  STARTING_MANA: 2,
  HALF_DAMAGE_MITIGATION_THRESHOLD: 100
};
