export type Config = {
  MAX_MAIN_DECK_SIZE: number;
  MAX_MAIN_DECK_CARD_COPIES: number;

  MAX_DESTINY_DECK_SIZE: number;
  MAX_DESTINY_DECK_CARD_COPIES: number;

  INITIAL_HAND_SIZE: number;
  INITAL_CARDS_IN_DESTINY_ZONE: number;
  MAX_HAND_SIZE: number;
  CARDS_DRAWN_PER_TURN: number;
  PLAYER_1_CARDS_DRAWN_ON_FIRST_TURN: number;
  PLAYER_2_CARDS_DRAWN_ON_FIRST_TURN: number;
  SHUFFLE_DECK_ON_GAME_START: boolean;

  ATTACK_ZONE_SLOTS: number;
  DEFENSE_ZONE_SLOTS: number;

  MAX_EQUIPPED_ARTIFACTS: number;

  SUMMONING_SICKNESS: boolean;
  ALLOW_PLAYER_1_TURN_1_ATTACK: boolean;
};

export const defaultConfig: Config = {
  MAX_MAIN_DECK_SIZE: 39,
  MAX_MAIN_DECK_CARD_COPIES: 3,

  MAX_DESTINY_DECK_SIZE: 10,
  MAX_DESTINY_DECK_CARD_COPIES: 1,

  INITIAL_HAND_SIZE: 5,
  INITAL_CARDS_IN_DESTINY_ZONE: 0,
  MAX_HAND_SIZE: 999,
  SHUFFLE_DECK_ON_GAME_START: true,
  CARDS_DRAWN_PER_TURN: 2,
  PLAYER_1_CARDS_DRAWN_ON_FIRST_TURN: 1,
  PLAYER_2_CARDS_DRAWN_ON_FIRST_TURN: 1,

  ATTACK_ZONE_SLOTS: 4,
  DEFENSE_ZONE_SLOTS: 4,

  MAX_EQUIPPED_ARTIFACTS: 3,

  SUMMONING_SICKNESS: false,
  ALLOW_PLAYER_1_TURN_1_ATTACK: false
};
