export type Config = {
  HALF_DAMAGE_MITIGATION_THRESHOLD: number;

  STARTING_MANA: number;
  DEFAULT_MAX_MANA: number;
  DEFAULT_MANA_REGEN_PER_TURN?: number;

  STARTING_AP: 1;
  DEFAULT_AP_REGEN_PER_TURN: number;

  DEFAULT_ATTACK_AP_COST: number;
  DEFAULT_ABILITY_AP_COST: number;
  DEFAULT_MAX_MOVEMENTS_PER_TURN: number;

  WIN_VP_THRESHOLD: number;
};

export const defaultConfig: Config = {
  DEFAULT_MAX_MANA: 5,
  DEFAULT_MANA_REGEN_PER_TURN: 1,
  DEFAULT_AP_REGEN_PER_TURN: 2,
  DEFAULT_ATTACK_AP_COST: 1,
  DEFAULT_ABILITY_AP_COST: 1,
  DEFAULT_MAX_MOVEMENTS_PER_TURN: 3,
  STARTING_MANA: 2,
  STARTING_AP: 1,
  HALF_DAMAGE_MITIGATION_THRESHOLD: 50,
  WIN_VP_THRESHOLD: 10
};
